// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetCoreConfigManagement) DeepCopyInto(out *NetCoreConfigManagement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetCoreConfigManagement.
func (in *NetCoreConfigManagement) DeepCopy() *NetCoreConfigManagement {
	if in == nil {
		return nil
	}
	out := new(NetCoreConfigManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetCoreConfigManagement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetCoreConfigManagementList) DeepCopyInto(out *NetCoreConfigManagementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetCoreConfigManagement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetCoreConfigManagementList.
func (in *NetCoreConfigManagementList) DeepCopy() *NetCoreConfigManagementList {
	if in == nil {
		return nil
	}
	out := new(NetCoreConfigManagementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetCoreConfigManagementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetCoreConfigManagementSpec) DeepCopyInto(out *NetCoreConfigManagementSpec) {
	*out = *in
	if in.LinkedDeployments != nil {
		in, out := &in.LinkedDeployments, &out.LinkedDeployments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Config = in.Config
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetCoreConfigManagementSpec.
func (in *NetCoreConfigManagementSpec) DeepCopy() *NetCoreConfigManagementSpec {
	if in == nil {
		return nil
	}
	out := new(NetCoreConfigManagementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetCoreConfigManagementStatus) DeepCopyInto(out *NetCoreConfigManagementStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetCoreConfigManagementStatus.
func (in *NetCoreConfigManagementStatus) DeepCopy() *NetCoreConfigManagementStatus {
	if in == nil {
		return nil
	}
	out := new(NetCoreConfigManagementStatus)
	in.DeepCopyInto(out)
	return out
}
