apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cm-operator
  template:
    metadata:
      labels:
        name: cm-operator
    spec:
      serviceAccountName: cm-operator
      imagePullSecrets:
        - name: "reg-cred"
      containers:
        - name: cm-operator
          image: REPLACE_IMAGE
          command:
            - cm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cm-operator"
